Chore: Disable forceConsistentCasingInFileNames because of issues in OSX
See
https://github.com/Microsoft/TypeScript/issues/17617

Since we added typeRoots, typescript fails in OSX with messages like:

error TS1149: File name '/users/jhernandez/dev/marvin/node_modules/@types/assets-webpack-plugin/index.d.ts' differs from already included file name '/Users/jhernandez/dev/marvin/node_modules/@types/assets-webpack-plugin/index.d.ts' only in casing.

This patch fixes the OSX problems by disabling forceConsistentCasingInFileNames until the issue is resolved.

Change-Id: Icb1af707d8f368069518a25227540987f6db06b9