Fix: escape start script wildcard
The package.json start script should escape its task wildcard argument
to forbid shell completion. Previously, when a file named `dev:foo`
existed, the following error occurred:

  ERROR: Task not found: "dev:foo"

Also, super minor formatting change to place `-s` arguments
consistently.

Change-Id: I724b29c82b5db50b0b3842bb9563c31361f909d8